# Generated by Django 5.0.4 on 2024-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=150)),
                ('song_link', models.FileField(upload_to='songs')),
            ],
        ),
    ]
