# Generated by Django 5.0.4 on 2024-05-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashler', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Lib',
        ),
    ]
