# Generated by Django 5.0.4 on 2024-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashler', '0004_rename_library_lib'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib',
            name='song_id',
            field=models.IntegerField(null=True),
        ),
    ]
