# Generated by Django 5.0.4 on 2024-05-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addsongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=150)),
                ('song_link', models.FileField(upload_to='songs')),
                ('song_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
