# Generated by Django 5.0.4 on 2024-05-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songadmin', '0002_addsongs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addsong',
        ),
    ]
